"""followers

Revision ID: 614688f17c08
Revises: 22aa440866a3
Create Date: 2019-06-13 21:57:24.166139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614688f17c08'
down_revision = '22aa440866a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.add_column('post', sa.Column('body', sa.String(length=140), nullable=True))
    op.drop_column('post', 'query')
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    op.add_column('post', sa.Column('query', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'body')
    op.drop_table('followers')
    # ### end Alembic commands ###
